import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import streamlit as st  # noqa: E402

from components import ui  # noqa: E402

st.title("About SafeRoute AI")
st.caption("Final-year project: an AI-powered safe route recommendation system.")

st.markdown("""
### SDG connection
The project supports **SDG 11: Sustainable Cities and Communities**, especially **Target 11.2** (safe, affordable,
accessible and sustainable transport systems for all, with attention to people in vulnerable situations such as
women, children, older people and persons with disabilities). It also connects to **SDG 3: Good Health and
Well-Being**, because road injuries and unsafe journeys harm health.

### Problem
Navigation apps rank routes by time or distance. The fastest option can pass poorly lit streets, busy junctions or
areas with a history of accidents, and what counts as risky depends on who is travelling and when. A student walking
at 10 PM and a senior citizen crossing at noon face very different risks.

### Solution
SafeRoute AI compares route alternatives on a **predicted safety score** next to travel time:

1. The user enters a start, destination, travel mode, traveler profile, date and time.
2. The system builds three route alternatives and the conditions along each (lighting, traffic, pedestrians, accident
   history, road condition, weather, time of day and more).
3. A machine learning model predicts a 0-100 safety score for every route (and for individual junctions).
4. The factors behind each score are explained.
5. An AI agent reads those numbers and gives a personalised recommendation, and answers follow-up questions.
6. **What If?** re-runs the pipeline under new conditions (night, rain, more traffic, a different profile).

### The ML model
- **Model:** Random Forest regressor (scikit-learn) with one-hot encoding for categories. A Ridge baseline and
  gradient boosting are compared on the Safety Insights page.
- **Data:** 20,000 rows of **synthetic** data generated by documented rules plus noise. It is **not real safety data**.
- **Output:** a score from 0 to 100. **70-100 Low risk, 40-69 Medium risk, 0-39 High risk.**
- **Explainability:** the model's feature importance, plus per-route factor effects (each group of features is
  replaced by typical values and the score change is measured) and exact Shapley attribution for What If? changes.
- **Recommendation rule:** recommendation score = predicted safety score minus a small penalty per extra minute
  compared with the fastest route (0.35 point per minute when walking, 0.40 cycling, 0.50 public transport,
  0.60 car).

### The AI agent
The agent re-runs the model for the current plan, optionally runs a What If? scenario if the question mentions one
(a time, weather, traffic change, profile or mode), and then writes the answer from those numbers. If an
OpenAI-compatible API key is configured on the backend it uses that language model, otherwise a built-in offline
writer produces the answer from the same facts. It is told never to claim a route is safe and to say what it does
not know.

### Limitations
- All data is **synthetic** and routes are a **simulation**, so scores do not reflect real streets, crime or accidents.
- Place names map to approximate demo coordinates for Hyderabad; any other text gets a stable simulated location.
- No live traffic, weather, incident or road-closure data is used.
- Explanations are approximations of the model's behaviour, not causal proof.
- A real deployment would need real, regularly updated data and validation with local authorities and users.
""")
ui.disclaimer()
